# Site settings
title: streamzone
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://streamzone.io" # the base hostname & protocol for your site

twitter_username: congphuong32
github_username: congphuong

# Build settings
markdown: kramdown
